name: Run Newman Tests

on: [push, pull_request]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm i

      - name: Install Newman and Allure Reporter
        run: |
          npm install newman
          npm install newman-allure-reporter

      - name: Run Postman Collection with Allure Reporter
        run: newman run Petstore.postman_collection.json -r allure,cli --reporter-allure-export ./allure-results
        continue-on-error: true  # Continue even if the test fails

      - name: Setup Allure Report
        uses: actions/setup-allure@v2
        with:
          allure-version: "2.16.1" # specify the version of Allure you want to use

      - name: Generate Allure Report
        run: allure serve ./allure-results
        continue-on-error: true  # Continue even if the report generation fails

      - name: Commit and push allure report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./allure-results
          git commit -m "Add Allure test report"
          git push origin report
        continue-on-error: true  # Continue even if the commit fails
