name: Run Newman Tests

on: [push, pull_request]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm i

      - name: Install Newman
        run: npm install newman

      - name: Run Postman Collection
        run: newman run Petstore.postman_collection.json -r html,cli --reporter-html-export newman-report.html

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: report
          folder: .

      - name: Commit and push report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add newman-report.html
          git commit -m "Add Newman test report"
          git push origin report
